// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAZmuzH5cVQVP_RN9yYmNxcLsuX4gFCZ8',
    appId: '1:1922534801:web:65730988780c51de94de30',
    messagingSenderId: '1922534801',
    projectId: 'crow-92201',
    authDomain: 'crow-92201.firebaseapp.com',
    databaseURL: 'https://crow-92201-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crow-92201.appspot.com',
    measurementId: 'G-13FMGPK3Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'api-key',
    appId: '1:1922534801:android:4e3c8830dc7eacd794de30',
    messagingSenderId: '1922534801',
    projectId: 'crow-92201',
    databaseURL: 'https://crow-92201-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crow-92201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'apikey',
    appId: '1:1922534801:ios:33647d9f7721c7aa94de30',
    messagingSenderId: '1922534801',
    projectId: 'crow-92201',
    databaseURL: 'https://crow-92201-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crow-92201.appspot.com',
    iosBundleId: 'com.agaafar.crow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'apikey',
    appId: '1:1922534801:ios:b1966f16f608c9a694de30',
    messagingSenderId: '1922534801',
    projectId: 'crow-92201',
    databaseURL: 'https://crow-92201-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'crow-92201.appspot.com',
    iosBundleId: 'com.agaafar.crow.RunnerTests',
  );
}
